### ISSUE TITLE
--inventory-path throwing an error on v0.29.x

### ISSUE THREAD

**Issue by jamesglennan** [kapicorp/kapitan#621] opened 2020-10-05 16:38 UTC
**Describe the bug/feature**
An error is thrown when trying to compile templates that are not in the current directory

**To Reproduce**
1. Be in the parent directory
2. Attempt to compile the templates using `kapitan compile --inventory-path ./deployments/inventory --search-paths ./deployments --output-path deployments`
3. Get an Error
```
Inventory not found in search paths: ['/Users/jamesglennan/code/cert-manager/deployments', '/var/folders/0d/qdh7jkkj65153mzkmblmfnvm0000gn/T/tmp12g0g5wq.kapitan']
```

**Expected behavior**
Expect templates to compile, works on v0.28 (and below afaik)

** If it's a bug (please complete the following information):**
 - `python --version`: Python 3.8.5
 - `pip3 --version`:  pip 20.1.1
 - `Are you using pyenv or virtualenv?` No

**Additional context**
Works if you cd into the directory and just run `kapitan compile`
Workaround is to use v0.28 or cd into dir.

**Comment by ramaro** [comment] 2020-10-05 17:05
@jamesglennan thanks for reporting! Looks like we need a test for this :) Will be looking at it soon...

**Comment by uberspot** [comment] 2020-10-06 08:02
Just for completeness, could you also try your kapitan compile command with --inventory-path `./deployments/` ? 
And do --verbose if possible in either run?

**Comment by jamesglennan** [comment] 2020-10-06 08:43
```
kapitan compile --inventory-path ./deployments/inventory --search-paths ./deployments --output-path deployments --verbose
2020-10-06 09:42:06,395 git.cmd      DEBUG    Popen(['git', 'version'], cwd=/Users/jamesglennan/code/navika/cert-manager, universal_newlines=False, shell=None, istream=None)
2020-10-06 09:42:06,407 git.cmd      DEBUG    Popen(['git', 'version'], cwd=/Users/jamesglennan/code/navika/cert-manager, universal_newlines=False, shell=None, istream=None)
2020-10-06 09:42:06,431 kapitan.cli  DEBUG    Running with args: Namespace(cache=False, cache_paths=[], embed_refs=False, fetch=False, force=False, func=<function trigger_compile at 0x10e4eb430>, ignore_version_check=False, indent=2, inventory_path='./deployments/inventory', jinja2_filters='lib/jinja2_filters.py', labels=[], output_path='deployments', parallelism=4, prune=False, quiet=False, refs_path='./refs', reveal=False, schemas_path='./schemas', search_paths=['./deployments'], subparser_name='compile', targets=[], validate=False, verbose=True)
2020-10-06 09:42:06,452 kapitan.resources DEBUG    Using reclass inventory config defaults
2020-10-06 09:42:06,472 kapitan.utils DEBUG    hashable_lru_cache: True not serialiseable, using generic lru_cache instead
2020-10-06 09:42:06,478 kapitan.targets DEBUG    validating target name matches the name of yml file production
2020-10-06 09:42:06,478 kapitan.targets DEBUG    load_target_inventory: found valid kapitan target production
2020-10-06 09:42:06,478 kapitan.utils DEBUG    hashable_lru_cache: True not serialiseable, using generic lru_cache instead
2020-10-06 09:42:06,482 kapitan.targets DEBUG    validating target name matches the name of yml file integration
2020-10-06 09:42:06,482 kapitan.targets DEBUG    load_target_inventory: found valid kapitan target integration
2020-10-06 09:42:06,482 kapitan.utils DEBUG    hashable_lru_cache: True not serialiseable, using generic lru_cache instead
2020-10-06 09:42:06,487 kapitan.targets DEBUG    validating target name matches the name of yml file dev
2020-10-06 09:42:06,487 kapitan.targets DEBUG    load_target_inventory: found valid kapitan target dev
2020-10-06 09:42:06,949 git.cmd      DEBUG    Popen(['git', 'version'], cwd=/Users/jamesglennan/code/navika/cert-manager, universal_newlines=False, shell=None, istream=None)
2020-10-06 09:42:06,951 git.cmd      DEBUG    Popen(['git', 'version'], cwd=/Users/jamesglennan/code/navika/cert-manager, universal_newlines=False, shell=None, istream=None)
2020-10-06 09:42:06,951 git.cmd      DEBUG    Popen(['git', 'version'], cwd=/Users/jamesglennan/code/navika/cert-manager, universal_newlines=False, shell=None, istream=None)
2020-10-06 09:42:06,953 git.cmd      DEBUG    Popen(['git', 'version'], cwd=/Users/jamesglennan/code/navika/cert-manager, universal_newlines=False, shell=None, istream=None)
2020-10-06 09:42:06,963 git.cmd      DEBUG    Popen(['git', 'version'], cwd=/Users/jamesglennan/code/navika/cert-manager, universal_newlines=False, shell=None, istream=None)
2020-10-06 09:42:06,965 git.cmd      DEBUG    Popen(['git', 'version'], cwd=/Users/jamesglennan/code/navika/cert-manager, universal_newlines=False, shell=None, istream=None)
2020-10-06 09:42:06,967 git.cmd      DEBUG    Popen(['git', 'version'], cwd=/Users/jamesglennan/code/navika/cert-manager, universal_newlines=False, shell=None, istream=None)
2020-10-06 09:42:06,968 git.cmd      DEBUG    Popen(['git', 'version'], cwd=/Users/jamesglennan/code/navika/cert-manager, universal_newlines=False, shell=None, istream=None)
2020-10-06 09:42:06,990 kapitan.inputs.base DEBUG    Compiling /Users/jamesglennan/code/navika/cert-manager/deployments/components/app
2020-10-06 09:42:06,991 kapitan.inputs.base DEBUG    Compiling /Users/jamesglennan/code/navika/cert-manager/deployments/components/app
2020-10-06 09:42:06,992 kapitan.inputs.base DEBUG    Compiling /Users/jamesglennan/code/navika/cert-manager/deployments/components/app
2020-10-06 09:42:07,004 kapitan.targets DEBUG    Compile pool terminated
2020-10-06 09:42:07,004 kapitan.targets ERROR

2020-10-06 09:42:07,004 kapitan.targets ERROR    Inventory not found in search paths: ['/Users/jamesglennan/code/navika/cert-manager/deployments', '/var/folders/0d/qdh7jkkj65153mzkmblmfnvm0000gn/T/tmpjgveda4z.kapitan']
Compile error: failed to compile target: production
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/jamesglennan/Library/Python/3.8/lib/python/site-packages/kapitan/inputs/base.py", line 70, in compile_input_path
    self.compile_file(
  File "/Users/jamesglennan/Library/Python/3.8/lib/python/site-packages/kapitan/inputs/jinja2.py", line 35, in compile_file
    context["inventory"] = inventory(self.search_paths, target_name, self.inventory_path)
  File "/Users/jamesglennan/Library/Python/3.8/lib/python/site-packages/kapitan/resources.py", line 265, in inventory
    raise InventoryError(f"Inventory not found in search paths: {search_paths}")
kapitan.errors.InventoryError: Inventory not found in search paths: ['/Users/jamesglennan/code/navika/cert-manager/deployments', '/var/folders/0d/qdh7jkkj65153mzkmblmfnvm0000gn/T/tmpjgveda4z.kapitan']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/jamesglennan/Library/Python/3.8/lib/python/site-packages/kapitan/targets.py", line 453, in compile_target
    input_compiler.compile_obj(comp_obj, ext_vars, **kwargs)
  File "/Users/jamesglennan/Library/Python/3.8/lib/python/site-packages/kapitan/inputs/base.py", line 55, in compile_obj
    self.compile_input_path(input_path, comp_obj, ext_vars, **kwargs)
  File "/Users/jamesglennan/Library/Python/3.8/lib/python/site-packages/kapitan/inputs/base.py", line 80, in compile_input_path
    raise CompileError("{}\nCompile error: failed to compile target: {}".format(e, target_name))
kapitan.errors.CompileError: Inventory not found in search paths: ['/Users/jamesglennan/code/navika/cert-manager/deployments', '/var/folders/0d/qdh7jkkj65153mzkmblmfnvm0000gn/T/tmpjgveda4z.kapitan']
Compile error: failed to compile target: production
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jamesglennan/Library/Python/3.8/lib/python/site-packages/kapitan/targets.py", line 126, in compile_targets
    [p.get() for p in pool.imap_unordered(worker, target_objs) if p]
  File "/Users/jamesglennan/Library/Python/3.8/lib/python/site-packages/kapitan/targets.py", line 126, in <listcomp>
    [p.get() for p in pool.imap_unordered(worker, target_objs) if p]
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
kapitan.errors.CompileError: Inventory not found in search paths: ['/Users/jamesglennan/code/navika/cert-manager/deployments', '/var/folders/0d/qdh7jkkj65153mzkmblmfnvm0000gn/T/tmpjgveda4z.kapitan']
Compile error: failed to compile target: production
2020-10-06 09:42:07,006 kapitan.targets DEBUG    Removed /var/folders/0d/qdh7jkkj65153mzkmblmfnvm0000gn/T/tmpjgveda4z.kapitan
```

**Comment by jamesglennan** [comment] 2020-10-06 08:43
```
kapitan compile --inventory-path ./deployments/ --search-paths ./deployments --output-path deployments
Inventory reclass error: inventory not found


No such directory: ./deployments/targets
```

**Comment by jamesglennan** [comment] 2020-10-06 08:44
Cheers for getting on this team :)

**Comment by AlphaRoy14** [comment] 2020-10-06 10:42
### With `--inventory-path` specified
I think the issue is that `inventory_reclass()` gets called first with using `kapitan compile --inventory-path ./deployments/inventory --search-paths ./deployments --output-path deployments`

https://github.com/deepmind/kapitan/blob/1b8b6b203e20cdfd58cc1a4a29fbd5f705f83775/kapitan/resources.py#L294

with the `inventory_path=./deployments/inventory`

Later, the `inventory()` function gets called from `jinja2.py`. https://github.com/deepmind/kapitan/blob/1b8b6b203e20cdfd58cc1a4a29fbd5f705f83775/kapitan/resources.py#L248

Which tries to set the `full_inv_path` using:
https://github.com/deepmind/kapitan/blob/1b8b6b203e20cdfd58cc1a4a29fbd5f705f83775/kapitan/resources.py#L259

This sets the full_inv_path as `/Users/xyz/deployments/./deployments/inventory`, which raises the error.
### Without --inventory-path specified
`inventory_reclass()` raises `Inventory reclass error: inventory not found` as default inventory path is `./inventory`

### Solution
May be we can define a function which will check if `--inventory-path /path ` is specified and then set  `full_inv_path = /path`
Else,` full_inv_path = os.path.join(search_path, "./inventory")` and save the `full_inv_path` to cache?

**Comment by uberspot** [comment] 2020-10-07 07:45
> May be we can define a function which will check if `--inventory-path /path ` is specified and then set `full_inv_path = /path`
> Else,` full_inv_path = os.path.join(search_path, "./inventory")` and save the `full_inv_path` to cache?

That could work. Alternatively a simple solution is also checking in that inventory() function whether the inventory_path =="inventory/" since that's the default. If not, `full_inv_path = /path` else `full_inv_path = os.path.join(search_path, "./inventory")`. It's selfcontained and you don't have to worry about cache state (?).

**Comment by AlphaRoy14** [comment] 2020-10-07 08:18
One potential issue could be in  case If `--inventory-path` is not specified. Then, I think the inventory path i.e `full_inv_path = os.path.join(search_path, "./inventory")` should be set at an earlier stage since `inventory_reclass()` is called before `inventory()`. Else `inventory_reclass()` will try to search for inventory in `./inventory` instead of `search_path/inventory` (?) In fact, the `full_inv_path` is only being set in the `inventory()` function which, afaik, only gets invoked from `kapitan/inputs/jinja2.py` 
https://github.com/deepmind/kapitan/blob/1b8b6b203e20cdfd58cc1a4a29fbd5f705f83775/kapitan/inputs/jinja2.py#L35

So it might be useful to set the `full_inv_path` in a more global scale?

**Comment by uberspot** [comment] 2020-10-07 10:04
I had a quick browse and all paths that lead to inventory_reclass() do get the correct path from args directly (?) so this might not be a problem.
I have a suspicion that the inventory( ) function's handling of the inventory path is an exception for jinja2 specifically (?).
@ramaro might have a better idea.

**Comment by ramaro** [comment] 2020-10-08 18:22
Hey @jamesglennan are you compiling the jsonnet version of cert-manager?

**Comment by ramaro** [comment] 2020-10-08 22:52
I think the issue is that `"inventory/"` is hardcoded in the kapitan.libjsonnet native function call at https://github.com/deepmind/kapitan/blob/master/kapitan/lib/kapitan.libjsonnet#L9
So setting the `--inventory-path` flag won't update the optional parameter in the `inventory()` native call. This wasn't very clever of us (me!) to write it this way. So I'm updating the default value to `null` which will default to the flag value.

I fixed it in my personal fork, do you want to give it a try? https://github.com/deepmind/kapitan/compare/master...ramaro:inventory_path_fix

**Comment by jamesglennan** [comment] 2020-10-09 07:55
No, we're using Jinja2, cert-manager is an example, but anything we try to compile seems to fail when specifying inventory

**Comment by jamesglennan** [comment] 2020-10-09 08:16
@ramaro Quick test and your fix seems to do the trick, thanks for getting on this so quick

**Comment by ramaro** [comment] 2020-10-09 09:32
@jamesglennan thanks for testing! PR on the way.

**Comment by jamesglennan** [comment] 2020-10-09 10:38
@ramaro Out of curiosity, what's the release schedule on Kapitan? Once a month? or thereabouts?

**Comment by uberspot** [comment] 2020-10-09 10:48
> @ramaro Out of curiosity, what's the release schedule on Kapitan? Twice a month? or thereabouts?

No official release schedule, mostly going based on needs. 
I can start 0.29.3 for you now. :)

**Comment by jamesglennan** [comment] 2020-10-10 09:40
```
kapitan compile --inventory-path deployments/inventory --search-paths deployments --output-path deployments Unknown (Non-Kapitan) Error occurred
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/jamesglennan/Library/Python/3.8/lib/python/site-packages/kapitan/targets.py", line 453, in compile_target
    input_compiler.compile_obj(comp_obj, ext_vars, **kwargs)
  File "/Users/jamesglennan/Library/Python/3.8/lib/python/site-packages/kapitan/inputs/base.py", line 54, in compile_obj
    self.compile_input_path(input_path, comp_obj, ext_vars, **kwargs)
  File "/Users/jamesglennan/Library/Python/3.8/lib/python/site-packages/kapitan/inputs/base.py", line 69, in compile_input_path
    self.compile_file(
  File "/Users/jamesglennan/Library/Python/3.8/lib/python/site-packages/kapitan/inputs/jinja2.py", line 35, in compile_file
    context["inventory"] = inventory(self.search_paths, target_name)
  File "/Users/jamesglennan/Library/Python/3.8/lib/python/site-packages/kapitan/resources.py", line 260, in inventory
    inventory_path = inventory_path_arg.inventory_path
AttributeError: 'NoneType' object has no attribute 'inventory_path'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jamesglennan/Library/Python/3.8/lib/python/site-packages/kapitan/targets.py", line 126, in compile_targets
    [p.get() for p in pool.imap_unordered(worker, target_objs) if p]
  File "/Users/jamesglennan/Library/Python/3.8/lib/python/site-packages/kapitan/targets.py", line 126, in <listcomp>
    [p.get() for p in pool.imap_unordered(worker, target_objs) if p]
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
AttributeError: 'NoneType' object has no attribute 'inventory_path'

```

**Comment by jamesglennan** [comment] 2020-10-10 09:44
Should we re-open this? When i tested, i ran it with `python3 . ...args` using full path
I just tested the installed version with full path and same error?

**Comment by ramaro** [comment] 2020-10-10 09:51
Interesting... Yes let's reopen this. Thanks for your findings!

**Comment by ramaro** [comment] 2020-12-03 10:34
Hey @jamesglennan if you can give this fix https://github.com/deepmind/kapitan/pull/661 a shot, please let me know how it works for you 👍  It's now merged in master

**Comment by jamesglennan** [comment] 2020-12-03 12:06
@ramaro Running it from the cli with python command works perfectly (same as last time) but im getting an error when i try and run the container version, or build the binary
```
Successfully built 174271bace8a
Successfully tagged kapitan:latest
----- Testing run of docker image -----
docker run -ti --rm kapitan --help
Traceback (most recent call last):
  File "/opt/venv/bin/kapitan", line 5, in <module>
    from kapitan.cli import main
  File "/opt/venv/lib/python3.7/site-packages/kapitan/cli.py", line 23, in <module>
    from kapitan.refs.cmd_parser import handle_refs_command
  File "/opt/venv/lib/python3.7/site-packages/kapitan/refs/cmd_parser.py", line 17, in <module>
    from kapitan.resources import inventory_reclass
  File "/opt/venv/lib/python3.7/site-packages/kapitan/resources.py", line 28, in <module>
    import reclass
ModuleNotFoundError: No module named 'reclass'
make: *** [test_docker] Error 1
```
I'm guessing this is more related to release/install problems?

**Comment by ramaro** [comment] 2020-12-03 12:14
Hey thanks for checking. That looks to be a release problem indeed. cc @uberspot

**Comment by uberspot** [comment] 2020-12-04 08:54
Hmm, yeah that seems like it didn't git pull the reclass submodule when building on docker. 
I'll start another release with this fix and see if this happens on Travis as well.

**Closed** 2023-03-09 08:59 UTC
Labels: bug
