### ISSUE TITLE
Short-Key usage lead to AttributeError: NoneType 

### ISSUE THREAD

**Issue by Moep90** [kapicorp/kapitan#784] opened 2021-09-27 17:01 UTC
# Describe the bug/feature
Shortkey's seams to not work propperly and some are duplicated for different actions
i = init = inventory
```bash
$ ./kapitan --help
usage: kapitan [-h] [--version]
               {eval,e,compile,c,inventory,i,searchvar,sv,secrets,s,refs,r,lint,l,init,validate,v}
[...]
positional arguments:
  {eval,e,compile,c,inventory,i,searchvar,sv,secrets,s,refs,r,lint,l,init,validate,v}
                        commands
    eval (e)            evaluate jsonnet file
    compile (c)         compile targets
    inventory (i)       show inventory
    searchvar (sv)      show all inventory files where var is declared
    secrets (s)         (DEPRECATED) please use refs
    refs (r)            manage refs
    lint (l)            linter for inventory and refs
    init (i)            initialize a directory with the recommended kapitan
                        project skeleton.
    validate (v)        validates the compile output against schemas as
                        specified in inventory
```

# To Reproduce
Run `$ ./kapitan c`

# Expected behavior
`$ ./kapitan c` compiles the targets as `$ ./kapitan compile` does

# Screenshots/Panic output
```bash
$ ./kapitan c
Unknown (Non-Kapitan) Error occurred
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/opt/venv/lib/python3.7/site-packages/kapitan/targets.py", line 464, in compile_target
    input_compiler.compile_obj(comp_obj, ext_vars, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/kapitan/inputs/base.py", line 55, in compile_obj
    self.compile_input_path(input_path, comp_obj, ext_vars, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/kapitan/inputs/base.py", line 77, in compile_input_path
    **kwargs,
  File "/opt/venv/lib/python3.7/site-packages/kapitan/inputs/jinja2.py", line 39, in compile_file
    context["inventory"] = inventory(self.search_paths, target_name)
  File "/opt/venv/lib/python3.7/site-packages/kapitan/resources.py", line 264, in inventory
    inventory_path = inventory_path_arg.inventory_path
AttributeError: 'NoneType' object has no attribute 'inventory_path'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/kapitan/targets.py", line 136, in compile_targets
    [p.get() for p in pool.imap_unordered(worker, target_objs) if p]
  File "/opt/venv/lib/python3.7/site-packages/kapitan/targets.py", line 136, in <listcomp>
    [p.get() for p in pool.imap_unordered(worker, target_objs) if p]
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
AttributeError: 'NoneType' object has no attribute 'inventory_path'


'NoneType' object has no attribute 'inventory_path'

```

# If it's a bug (please complete the following information):
```bash
$ cat ./kapitan 
#!/bin/bash
set -o nounset -o pipefail -o noclobber -o errexit

DIR=$(dirname ${BASH_SOURCE[0]})
ABS_PATH=$(cd "${DIR}"; pwd)

KAPITAN_IMAGE=kapicorp/kapitan:v0.30.0-rc.0

if hash kapitan 2> /dev/null
then
  KAPITAN_BINARY=kapitan
else
  KAPITAN_BINARY="docker run --rm -i -u $UID --network host -w /src \
  -v $PWD:/src:delegated \
  ${KAPITAN_IMAGE}"
fi

exec ${KAPITAN_BINARY} "$@"
```

**Additional context**

**Comment by ramaro** [comment] 2021-10-30 08:44
Hey @Moep90 I'm assuming you're only using the docker image for reproduce this? I can't reproduce it using the pip package.

**Comment by dhorbach** [comment] 2022-05-17 10:12
@ramaro I think this one is also fixed in https://github.com/kapicorp/kapitan/pull/837. Duplicated alias "i" for "init" was removed.

**Comment by ramaro** [comment] 2022-05-17 10:14
@dhorbach it is indeed, thanks again!

**Closed by ramaro** 2022-05-17 10:14 UTC
Labels: bug
